### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by abe33** [ArnaudRinquin/atom-zentabs#19]
[Enter steps to reproduce below:]

1. Execute the `pane:split-right` command when there's just one pane on the screen
2. The pane creation is prevented, instead an error is raised.

**Atom Version**: 0.180.0-2dac7fd
**System**: Mac OS X 10.10.2
**Thrown From**: [zentabs](https://github.com/ArnaudRinquin/atom-zentabs) package, v0.8.1

### Stack Trace

Uncaught TypeError: object is not a function

```
At /Users/cedric/.atom/packages/zentabs/lib/zentabs.coffee:33

TypeError: object is not a function
  at /Users/cedric/.atom/packages/zentabs/lib/zentabs.coffee:33:22
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:127:16
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:319:27)
  at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app/src/pane.js:111:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:121:13)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:174:19)
  at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:714:23)
  at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app/src/pane.js:682:19)
  at atom-pane.atom.commands.add.pane:split-right (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:226:30)

```

### Commands

```
     -1:41.9 editor:select-to-end-of-word (atom-text-editor.editor)
     -1:40.3 core:save (atom-text-editor.editor)
     -1:33.7 core:move-down (atom-text-editor.editor)
     -1:33.5 core:move-to-bottom (atom-text-editor.editor)
     -1:33.2 docblockr:parse-enter (atom-text-editor.editor)
     -1:33.2 editor:newline (atom-text-editor.editor)
     -1:31.1 docblockr:parse-enter (atom-text-editor.editor)
     -1:31.1 editor:newline (atom-text-editor.editor)
  2x -1:28.8 core:save (atom-text-editor.editor)
     -1:16.2 docblockr:parse-enter (atom-text-editor.editor)
     -1:16.2 editor:newline (atom-text-editor.editor)
     -1:12.8 core:save (atom-text-editor.editor)
     -1:12.4 docblockr:parse-enter (atom-text-editor.editor)
     -1:12.4 editor:newline (atom-text-editor.editor)
     -1:09.6 core:save (atom-text-editor.editor)
     -0:01.5 pane:split-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap-symbols",
      "preview-tabs",
      "crosshairs",
      "coffee-compile",
      "travis-ci-status",
      "enhanced-package-list",
      "themed-settings"
    ],
    "themes": [
      "spacegray-dark-ui",
      "spacegray-dark-syntax"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.5.3
Sublime-Style-Column-Selection, v1.2.3
atom-color-highlight, v3.0.8
autocomplete-plus, v2.1.6
bezier-curve-editor, v0.6.5
block-travel, v1.0.2
bug-report, v0.5.5
caniuse, v0.5.3
cut-line, v0.10.0
docblockr, v0.5.8
error-status, v0.3.3
figlet, v0.3.0
file-icons, v1.4.10
highlight-selected, v0.9.0
language-generic-config, v0.1.3
language-haml, v0.15.0
language-jade, v0.3.0
language-sass, v0.34.0
minimap, v4.1.4
minimap-color-highlight, v4.0.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-highlight-selected, v4.0.0
minimap-selection, v4.0.1
php-twig, v3.0.0
project-palette-finder, v2.4.15
red-wavy-underline, v0.2.4
spacegray-dark-syntax, v0.2.0
spacegray-dark-ui, v0.6.0
tabs-to-spaces, v0.8.1
tree-view-breadcrumb, v0.4.0
tree-view-open-files, v0.2.3
view-tail-large-files, v0.1.10
white-cursor, v0.5.2
zentabs, v0.8.1

# Dev
atom-color-highlight, v3.0.8
bezier-curve-editor, v0.6.5
deprecation-cop, v0.10.0
figlet, v0.3.0
minimap, v4.1.4
minimap-color-highlight, v4.0.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-highlight-selected, v4.0.0
minimap-selection, v4.0.1
project-palette-finder, v2.4.15
tree-view-breadcrumb, v0.4.0
```

**Comment by ArnaudRinquin** [comment]
Never publish when you are sick. Thanks @hmatsuda for the quick fix.
