### ISSUE TITLE
Uncaught TypeError: Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by mattheworiordan** [ArnaudRinquin/atom-zentabs#29]
I am using ZenTabs with Atom, and have configured keyboard shortcuts so that I can pin tabs without right clicking on a tab each time.  My keymap file looks like this:

```yaml
'atom-workspace':
  'cmd-\'': 'zentabs:pintab'
  'cmd-"': 'zentabs:unpintab'
```

If I open a file, and press `cmd-'`, I get this script error every time.  If I however right click and chose Pin Tab, and then use the shortcut afterwards, it works every time without an error.  Do you have any idea what may be causing this error?

BTW. It may be useful to have a command `zentabs:togglepintab` so that people can use one shortcut to pin and unpin tabs.

Thanks for a great plugin!

```
Uncaught TypeError: Cannot read property 'item' of undefined

/Users/mattheworiordan/.atom/packages/zentabs/lib/zentabs-controller.coffee:86
Hide Stack Trace
TypeError: Cannot read property 'item' of undefined
  at ZentabsController.module.exports.ZentabsController.pinTab (/Users/mattheworiordan/.atom/packages/zentabs/lib/zentabs-controller.coffee:86:16)
  at atom-workspace.<anonymous> (/Users/mattheworiordan/.atom/packages/zentabs/lib/zentabs-controller.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

**Comment by dorian-marchal** [comment]
Why were this issue closed ?

**Comment by rnemec** [comment]
This is still not working. Great plugin but for "the keyboard people" this bug is pretty ugly.
