### ISSUE TITLE
Failed to load the zentabs package

### ISSUE THREAD

**Issue by kevinsimper** [ArnaudRinquin/atom-zentabs#33]
1. Open atom

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [zentabs](https://github.com/ArnaudRinquin/atom-zentabs) package, v0.8.7

### Stack Trace

Failed to load the zentabs package

```
At Cannot find module 'emissary'

Error: Cannot find module 'emissary'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kevinsimper/.atom/packages/zentabs/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/lib/grim.js:4:13)
    at Object.<anonymous> (/Users/kevinsimper/.atom/packages/zentabs/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/grim/lib/grim.js:112:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kevinsimper/.atom/packages/zentabs/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:10:12)
    at Object.<anonymous> (/Users/kevinsimper/.atom/packages/zentabs/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:634:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kevinsimper/.atom/packages/zentabs/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at Object.<anonymous> (/Users/kevinsimper/.atom/packages/zentabs/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kevinsimper/.atom/packages/zentabs/lib/zentabs-controller.coffee:2:13)
    at Object.<anonymous> (/Users/kevinsimper/.atom/packages/zentabs/lib/zentabs-controller.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "atom-pair",
      "wakatime",
      "jshint",
      "react"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "zentabs": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
auto-update-packages, v1.0.0
autocomplete-modules, v1.4.1
editorconfig, v1.2.4
emmet, v2.4.1
language-babel, v2.15.4
language-docker, v1.1.6
language-elixir, v0.11.0
language-jade, v0.6.3
monokai, v0.18.0
nuclide-code-format, v0.0.35
synced-sidebar, v0.4.3
view-tail-large-files, v0.2.1
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by ArnaudRinquin** [comment]
The error states that the `emissary` module can't be found. 

`zentabs` doesn't depends directly on it but indirectly (through `atom-zentabs > atom-space-pen-views > space-pen > grim > emissary`).

Anyway, this is definitely not a `zentabs` bug but a `apm / npm install` issue. My advice is to uninstall / reinstall the package and you should be fine.

**Comment by kevinsimper** [comment]
:+1: Your were right!
