### ISSUE TITLE
`Zentabs: Pintab` command doesn't pin the current tab

### ISSUE THREAD

**Issue by dorian-marchal** [ArnaudRinquin/atom-zentabs#35]
When I execute the `Zentabs: Pintab` command via <kbd>Ctrl + Shift + P</kbd>, I expect my current tab to be pinned.
Currently, I can only pin a tab by right clicking on it.

**Comment by rnemec** [comment]
I second that.

Reproduce
1. Open a file (something.js)
2. Shift-CMD-P, type "pin", <ENTER>

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [zentabs](https://github.com/ArnaudRinquin/atom-zentabs) package, v0.8.7


### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /Users/rnemec/.atom/packages/zentabs/lib/zentabs-controller.coffee:87

TypeError: Cannot read property 'item' of undefined
    at ZentabsController.module.exports.ZentabsController.pinTab (/Users/rnemec/.atom/packages/zentabs/lib/zentabs-controller.coffee:87:16)
    at atom-workspace.<anonymous> (/Users/rnemec/.atom/packages/zentabs/lib/zentabs-controller.coffee:1:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:51.9.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -0:42.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.2.0 fuzzy-finder:toggle-file-finder (div.panels)
     -0:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.2.0 zentabs:pintab (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "run-command2",
      "grunt-runner",
      "archive-view",
      "exception-reporting",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "language-xml",
      "metrics",
      "open-on-github",
      "package-generator",
      "release-notes",
      "symbols-view",
      "atom-ctags",
      "autocomplete-atom-api",
      "quick-highlight",
      "language-go",
      "welcome",
      "terminal-plus",
      "color-picker",
      "language-jade",
      "language-coffee-script",
      "language-sass",
      "link",
      "logo-file-icons",
      "selection-highlight",
      "minimap-highlight-selected",
      "minimap",
      "language-markdown",
      "markdown-preview",
      "markdown-folder",
      "language-ejs",
      "linter-eslint",
      "plantuml-viewer",
      "diagrams",
      "language-less",
      "language-property-list",
      "styleguide",
      "atom-typescript",
      "autocomplete-paths"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "no",
    "themes": [
      "seti-ui",
      "monokai"
    ]
  },
  "zentabs": {
    "manualMode": true,
    "maximumOpenedTabs": 7
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.41 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-ctags, v5.0.0 (inactive)
atom-typescript, v10.1.13 (inactive)
autocomplete-js-import, v1.2.1 (active)
autocomplete-paths, v1.0.5 (inactive)
color-picker, v2.2.3 (inactive)
diagrams, v0.23.4 (inactive)
double-tag, v0.4.0 (active)
editorconfig, v2.0.5 (active)
es6-javascript, v1.0.0 (inactive)
fold-lines, v0.2.1 (active)
highlight-selected, v0.11.2 (active)
language-ejs, v0.4.0 (inactive)
language-jade, v0.7.2 (inactive)
language-pug, v0.0.19 (active)
last-cursor-position, v0.9.0 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (inactive)
markdown-preview-enhanced, v0.8.9 (active)
monokai, v0.18.0 (active)
plantuml-viewer, v0.7.1 (inactive)
platformio-ide-terminal, v2.2.2 (active)
seti-classic, v0.10.1 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.4.0 (active)
todo-show, v1.8.0 (inactive)
toggle-read-only, v0.1.8 (active)
zentabs, v0.8.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by rnemec** [comment]
Works! Thanks guys!
